(define (sum-of-squares-two-largest x y z)
  (let* ((largest (max x y z))
         (second-largest (cond ((and (= x largest) (>= y z)) y)
                               ((and (= x largest) (< y z)) z)
                               ((and (= y largest) (>= x z)) x)
                               ((and (= y largest) (< x z)) z)
                               ((>= x y) x)
                               (else y)))) 
    (+ (square largest) (square second-largest))))

(define (square n) (* n n))
